package com.smt.entity;

// default package
// Generated 2013-8-14 16:10:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TAppAction generated by hbm2java
 */
@Entity
@Table(name = "t_app_action", catalog = "no1stage")
public class TAppAction implements java.io.Serializable {

	private Integer id;
	private int userid;
	private Date startdate;
	private Date enddate;
	private String title;
	private String address;

	public TAppAction() {
	}

	public TAppAction(int userid) {
		this.userid = userid;
	}

	public TAppAction(int userid, Date startdate, Date enddate, String title,
			String address) {
		this.userid = userid;
		this.startdate = startdate;
		this.enddate = enddate;
		this.title = title;
		this.address = address;
	}
	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	@Column(name = "userid")
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "startdate")
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Column(name = "enddate")
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}
	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
