package com.smt.entity;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// default package
// Generated 2013-8-19 21:18:05 by Hibernate Tools 3.4.0.CR1

/**
 * TAppTopImg generated by hbm2java
 */
@Entity
@Table(name = "t_app_top_img", catalog = "no1stage")
public class TAppTopImg implements java.io.Serializable {

	private int tid;
	private String turl;
	private String tmemo;
	private String tlink;
	private TAppTop tpid;
	@ManyToOne(targetEntity = TAppTop.class,cascade={CascadeType.MERGE})
	@JoinColumn(name="tpid",referencedColumnName="tid")
	public TAppTop getTpid() {
		return tpid;
	}
	public void setTpid(TAppTop tpid) {
		this.tpid = tpid;
	}
	public TAppTopImg() {
	}
	@Id
	@GeneratedValue()
	@Column(name = "tid", unique = true, nullable = false)
	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}
	@Column(name="turl")
	public String getTurl() {
		return this.turl;
	}

	public void setTurl(String turl) {
		this.turl = turl;
	}
	@Column(name="tmemo")
	public String getTmemo() {
		return this.tmemo;
	}

	public void setTmemo(String tmemo) {
		this.tmemo = tmemo;
	}	
	@Column(name="tlink")
	public String getTlink() {
		return this.tlink;
	}

	public void setTlink(String tlink) {
		this.tlink = tlink;
	}

}
