package com.smt.entity;
// default package
// Generated 2013-8-18 18:03:51 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TAppPoster generated by hbm2java
 */
@Entity
@Table(name = "t_app_poster", catalog = "no1stage")
public class TAppPoster implements java.io.Serializable {

	private int pid;
	private String title;
	private String content;
	private String pString;
	private String ptype;
	private Integer psort;
	private Integer pis;
	private String purl;
	private String plink;
	
	
	@Column(name="PLINK")
	public String getPlink() {
		return plink;
	}

	public void setPlink(String plink) {
		this.plink = plink;
	}

	public TAppPoster() {
	}

	public TAppPoster(int pid) {
		this.pid = pid;
	}

	public TAppPoster(int pid, String title, String content, String pString,
			String ptype, Integer psort, Integer pis, String purl) {
		this.pid = pid;
		this.title = title;
		this.content = content;
		this.pString = pString;
		this.ptype = ptype;
		this.psort = psort;
		this.pis = pis;
		this.purl = purl;
	}

	@Id
	@GeneratedValue()
	@Column(name = "PID", unique = true, nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}
	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	@Column(name = "CONTENT")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}
	@Column(name = "PDATE")
	public String getPString() {
		return this.pString;
	}

	public void setPString(String pString) {
		this.pString = pString;
	}
	@Column(name = "PTYPE")
	public String getPtype() {
		return this.ptype;
	}

	public void setPtype(String ptype) {
		this.ptype = ptype;
	}
	@Column(name = "PSORT")
	public Integer getPsort() {
		return this.psort;
	}

	public void setPsort(Integer psort) {
		this.psort = psort;
	}
	@Column(name = "PIS")
	public Integer getPis() {
		return this.pis;
	}

	public void setPis(Integer pis) {
		this.pis = pis;
	}
	@Column(name = "PURL")
	public String getPurl() {
		return this.purl;
	}

	public void setPurl(String purl) {
		this.purl = purl;
	}

}
