package com.smt.entity;

// default package
// Generated 2013-8-19 21:18:05 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
/**
 * TAppTop generated by hbm2java
 */
@Entity
@Table(name = "t_app_top", catalog = "no1stage")
public class TAppTop implements java.io.Serializable {

	private int tid;
	private String name;
	private String status;
	private TAppUserInfo userid;
	private String comment;
	private String tdate;
	private List<TAppTopImg> imgs = new  ArrayList<TAppTopImg>();

	
	@Column(name="tdate")
	public String getTdate() {
		return tdate;
	}
	@OneToMany(mappedBy="tpid",targetEntity=TAppTopImg.class,cascade=CascadeType.MERGE,
			fetch=FetchType.EAGER)
	public List<TAppTopImg> getImgs() {
		return imgs;
	}

	public void setImgs(List<TAppTopImg> imgs) {
		this.imgs = imgs;
	}

	public void setTdate(String tdate) {
		this.tdate = tdate;
	}

	public TAppTop() {
	}

	public TAppTop(int tid) {
		this.tid = tid;
	}
	@Id
	@GeneratedValue()
	@Column(name = "tid", unique = true, nullable = false)
	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}
	@Column(name="name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@Column(name="status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	@ManyToOne(targetEntity=TAppUserInfo.class)
	@JoinColumn(name="userid",referencedColumnName="userid")
	public TAppUserInfo getUserid() {
		return this.userid;
	}

	public void setUserid(TAppUserInfo userid) {
		this.userid = userid;
	}
	@Column(name="comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}
}
