package com.smt.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// default package
// Generated 2013-8-14 16:13:03 by Hibernate Tools 3.4.0.CR1

/**
 * TBaseArea generated by hbm2java
 */
@Entity
@Table(name = "t_base_area", catalog = "no1stage")
public class TBaseArea implements java.io.Serializable {

	private int aid;
	private String areaname;
	private int rootid;
	private Integer childcount;
	private Integer isdept;
	private Integer sortid;
	private int astatus;
	
	@Id
	@GeneratedValue
	@Column(name = "aid", unique = true, nullable = false)
	public int getAid() {
		return aid;
	}
	public void setAid(int aid) {
		this.aid = aid;
	}
	@Column(name = "areaname")
	public String getAreaname() {
		return areaname;
	}
	public void setAreaname(String areaname) {
		this.areaname = areaname;
	}
	@Column(name = "rootid")
	public int getRootid() {
		return rootid;
	}
	public void setRootid(int rootid) {
		this.rootid = rootid;
	}
	@Column(name = "childcount")
	public Integer getChildcount() {
		return childcount;
	}
	public void setChildcount(Integer childcount) {
		this.childcount = childcount;
	}
	@Column(name = "isdept")
	public Integer getIsdept() {
		return isdept;
	}
	public void setIsdept(Integer isdept) {
		this.isdept = isdept;
	}
	@Column(name = "sortid")
	public Integer getSortid() {
		return sortid;
	}
	public void setSortid(Integer sortid) {
		this.sortid = sortid;
	}
	@Column(name = "astatus")
	public int getAstatus() {
		return astatus;
	}
	public void setAstatus(int astatus) {
		this.astatus = astatus;
	}

	
}
